CREATE TABLE IF NOT EXISTS add_address(
    add_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    add_street      VARCHAR(255) NOT NULL,
    add_number      VARCHAR(255) NOT NULL,
    add_district    VARCHAR(255) NOT NULL,
    add_city_name   VARCHAR(255) NOT NULL,
    add_state_name  VARCHAR(255) NOT NULL,
    add_postal_code VARCHAR(20)  NOT NULL,
    add_complement  VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS sup_supplier(
    sup_id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sup_name           VARCHAR(255) NOT NULL,
    sup_legal_document VARCHAR(20)  NOT NULL UNIQUE,
    sup_email          VARCHAR(255),
    sup_phone          VARCHAR(20),
    sup_address_id     BIGINT,
    FOREIGN KEY (sup_address_id) REFERENCES add_address (add_id)
);

CREATE TABLE IF NOT EXISTS pro_product(
    pro_id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pro_name            VARCHAR(255)   NOT NULL,
    pro_barcode         VARCHAR(255)   NOT NULL UNIQUE,
    pro_category        VARCHAR(255)   NOT NULL,
    pro_supplier_id     BIGINT,
    pro_unit_price      DECIMAL(19, 2) NOT NULL,
    pro_measure_unit    VARCHAR(255)   NOT NULL,
    pro_stock_quantity  INTEGER        NOT NULL,
    pro_max_stock_level INTEGER        NOT NULL,
    pro_entry_date      DATE           NOT NULL,
    pro_description     VARCHAR(255),
    FOREIGN KEY (pro_supplier_id) REFERENCES sup_supplier (sup_id)
);