name: Continuous Delivery

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  modify-application-yml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Modify application.yml
        run: |
          sed -i "s|url:.*|url: ${{ secrets.DATASOURCE_URL }}|" src/main/resources/application.yml
          sed -i "s|username:.*|username: ${{ secrets.DATASOURCE_USERNAME }}|" src/main/resources/application.yml
          sed -i "s|password:.*|password: ${{ secrets.DATASOURCE_PASSWORD }}|" src/main/resources/application.yml

      - name: Modify profile and print
        run: |
          sed -i "s|^  active:.*|  active: default|" src/main/resources/application.yml
          grep "^spring.profiles.active" src/main/resources/application.yml | cut -d ":" -f 2-


  build:
    needs: modify-application-yml
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven
        run: mvn clean install

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            scp target/your-application.jar ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/path/to/deployment/directory
            ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} 'bash -s' < deploy_script.sh