name: Continuous Integration

on:
  pull_request:
    branches: [ '**' ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Build with Maven (skip Spring Boot run)
        run: mvn clean install -Dspring-boot.run.skip=true

      - name: Test
        run: mvn clean test
