name: Continuous Delivery

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download and configure application.yml
        run: |
          curl -o application.yml -u ${{ secrets.GITHUB_TOKEN }}:x-oauth-basic https://github.com/GilbertoJNJ/Config-files/blob/main/LogiStockApi-application.yml
          mv application.yml src/main/resources/application.yml

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn -B clean package

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            scp target/your-application.jar ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/path/to/deployment/directory
            ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} 'bash -s' < deploy_script.sh
